# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "82deb902f933ae6e6b3cccccd6f5463b"
name = "otp_registartion"
application_url = "https://validity-divided-amended-pencil.trycloudflare.com"
embedded = true

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_files,read_orders,read_products,write_customers,write_files,write_metaobject_definitions,write_metaobjects,write_products"

[auth]
redirect_urls = [ "https://validity-divided-amended-pencil.trycloudflare.com/api/auth" ]

[build]
automatically_update_urls_on_dev = true

[app_proxy]
url = "https://validity-divided-amended-pencil.trycloudflare.com/api/membership"
subpath = "membership"
prefix = "apps"
