# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1b706e4a05a3ac59e3b79a982daddecc"
name = "Membership Registration"
application_url = "https://membership-registration-9h9v.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_files,read_orders,read_products,write_customers,write_files,write_metaobject_definitions,write_metaobjects,write_products"

[auth]
redirect_urls = [ "https://membership-registration-9h9v.vercel.app/auth" ]

[app_proxy]
url = "https://membership-registration-9h9v.vercel.app/api/membership"
subpath = "membership"
prefix = "apps"
